apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-fase-4-payment-api-deployment
  labels:
    app: tech-challenge-fase-4-payment-api-deployment
spec:
  selector:
    matchLabels:
      app: tech-challenge-fase-4-payment-api
  template:
    metadata:
      labels:
        app: tech-challenge-fase-4-payment-api
    spec:
      containers:
        - name: tech-challenge-fase-4-payment-api
          image: leosaglia/tech-challenge-fase-4-payment-api
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: payment-api-secrets
                  key: POSTGRES_URL
            - name: PORT
              value: "3001"
            - name: PROCESSED_PAYMENT_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  name: payment-api-config
                  key: PROCESSED_PAYMENT_QUEUE_URL
            - name: CREATED_ORDER_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  name: payment-api-config
                  key: CREATED_ORDER_QUEUE_URL
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: payment-api-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: payment-api-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: payment-api-secrets
                  key: AWS_SESSION_TOKEN
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5
